version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server/db:/app/db
      - ./certs:/app/certs
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend
    restart: always
